// g:\Shubham Personal Projects\Personal projects\transcation_history\transcation_history\lib\folders\services.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'dataservice.dart';